using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;

namespace M.Repository
{
    public interface IQueryableAsyncExtensionsProxy
    {
        Task<List<object>> ToListAsync(IQueryable source);
        Task<List<object>> ToListAsync(IQueryable source, CancellationToken cancellationToken);
        Task<List<TSource>> ToListAsync<TSource>(IQueryable<TSource> source);
        Task<List<TSource>> ToListAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken);
        Task<TSource[]> ToArrayAsync<TSource>(IQueryable<TSource> source);
        Task<TSource[]> ToArrayAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken);
        Task<TSource> FirstAsync<TSource>(IQueryable<TSource> source);
        Task<TSource> FirstAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken);
        Task<TSource> FirstAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate);
        Task<TSource> FirstAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate, CancellationToken cancellationToken);
        Task<TSource> FirstOrDefaultAsync<TSource>(IQueryable<TSource> source);
        Task<TSource> FirstOrDefaultAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken);
        Task<TSource> FirstOrDefaultAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate);
        Task<TSource> FirstOrDefaultAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate, CancellationToken cancellationToken);
        Task<TSource> SingleAsync<TSource>(IQueryable<TSource> source);
        Task<TSource> SingleAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken);
        Task<TSource> SingleAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate);
        Task<TSource> SingleAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate, CancellationToken cancellationToken);
        Task<TSource> SingleOrDefaultAsync<TSource>(IQueryable<TSource> source);
        Task<TSource> SingleOrDefaultAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken);
        Task<TSource> SingleOrDefaultAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate);
        Task<TSource> SingleOrDefaultAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate, CancellationToken cancellationToken);
        Task<bool> ContainsAsync<TSource>(IQueryable<TSource> source, TSource item);
        Task<bool> ContainsAsync<TSource>(IQueryable<TSource> source, TSource item, CancellationToken cancellationToken);
        Task<bool> AnyAsync<TSource>(IQueryable<TSource> source);
        Task<bool> AnyAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken);
        Task<bool> AnyAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate);
        Task<bool> AnyAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate, CancellationToken cancellationToken);
        Task<bool> AllAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate);
        Task<bool> AllAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate, CancellationToken cancellationToken);
        Task<int> CountAsync<TSource>(IQueryable<TSource> source);
        Task<int> CountAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken);
        Task<int> CountAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate);
        Task<int> CountAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate, CancellationToken cancellationToken);
        Task<long> LongCountAsync<TSource>(IQueryable<TSource> source);
        Task<long> LongCountAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken);
        Task<long> LongCountAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate);
        Task<long> LongCountAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate, CancellationToken cancellationToken);
        Task<TSource> MinAsync<TSource>(IQueryable<TSource> source);
        Task<TSource> MinAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken);
        Task<TResult> MinAsync<TSource, TResult>(IQueryable<TSource> source, Expression<Func<TSource, TResult>> selector);
        Task<TResult> MinAsync<TSource, TResult>(IQueryable<TSource> source, Expression<Func<TSource, TResult>> selector, CancellationToken cancellationToken);
        Task<TSource> MaxAsync<TSource>(IQueryable<TSource> source);
        Task<TSource> MaxAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken);
        Task<TResult> MaxAsync<TSource, TResult>(IQueryable<TSource> source, Expression<Func<TSource, TResult>> selector);
        Task<TResult> MaxAsync<TSource, TResult>(IQueryable<TSource> source, Expression<Func<TSource, TResult>> selector, CancellationToken cancellationToken);
        Task<int> SumAsync(IQueryable<int> source);
        Task<int> SumAsync(IQueryable<int> source, CancellationToken cancellationToken);
        Task<int?> SumAsync(IQueryable<int?> source);
        Task<int?> SumAsync(IQueryable<int?> source, CancellationToken cancellationToken);
        Task<long> SumAsync(IQueryable<long> source);
        Task<long> SumAsync(IQueryable<long> source, CancellationToken cancellationToken);
        Task<long?> SumAsync(IQueryable<long?> source);
        Task<long?> SumAsync(IQueryable<long?> source, CancellationToken cancellationToken);
        Task<float> SumAsync(IQueryable<float> source);
        Task<float> SumAsync(IQueryable<float> source, CancellationToken cancellationToken);
        Task<float?> SumAsync(IQueryable<float?> source);
        Task<float?> SumAsync(IQueryable<float?> source, CancellationToken cancellationToken);
        Task<double> SumAsync(IQueryable<double> source);
        Task<double> SumAsync(IQueryable<double> source, CancellationToken cancellationToken);
        Task<double?> SumAsync(IQueryable<double?> source);
        Task<double?> SumAsync(IQueryable<double?> source, CancellationToken cancellationToken);
        Task<Decimal> SumAsync(IQueryable<Decimal> source);
        Task<Decimal> SumAsync(IQueryable<Decimal> source, CancellationToken cancellationToken);
        Task<Decimal?> SumAsync(IQueryable<Decimal?> source);
        Task<Decimal?> SumAsync(IQueryable<Decimal?> source, CancellationToken cancellationToken);
        Task<int> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, int>> selector);
        Task<int> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, int>> selector, CancellationToken cancellationToken);
        Task<int?> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, int?>> selector);
        Task<int?> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, int?>> selector, CancellationToken cancellationToken);
        Task<long> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, long>> selector);
        Task<long> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, long>> selector, CancellationToken cancellationToken);
        Task<long?> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, long?>> selector);
        Task<long?> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, long?>> selector, CancellationToken cancellationToken);
        Task<float> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, float>> selector);
        Task<float> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, float>> selector, CancellationToken cancellationToken);
        Task<float?> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, float?>> selector);
        Task<float?> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, float?>> selector, CancellationToken cancellationToken);
        Task<double> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, double>> selector);
        Task<double> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, double>> selector, CancellationToken cancellationToken);
        Task<double?> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, double?>> selector);
        Task<double?> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, double?>> selector, CancellationToken cancellationToken);
        Task<Decimal> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, Decimal>> selector);
        Task<decimal> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, Decimal>> selector, CancellationToken cancellationToken);
        Task<decimal?> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, Decimal?>> selector);
        Task<decimal?> SumAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, Decimal?>> selector, CancellationToken cancellationToken);
        Task<double> AverageAsync(IQueryable<int> source);
        Task<double> AverageAsync(IQueryable<int> source, CancellationToken cancellationToken);
        Task<double?> AverageAsync(IQueryable<int?> source);
        Task<double?> AverageAsync(IQueryable<int?> source, CancellationToken cancellationToken);
        Task<double> AverageAsync(IQueryable<long> source);
        Task<double> AverageAsync(IQueryable<long> source, CancellationToken cancellationToken);
        Task<double?> AverageAsync(IQueryable<long?> source);
        Task<double?> AverageAsync(IQueryable<long?> source, CancellationToken cancellationToken);
        Task<float> AverageAsync(IQueryable<float> source);
        Task<float> AverageAsync(IQueryable<float> source, CancellationToken cancellationToken);
        Task<float?> AverageAsync(IQueryable<float?> source);
        Task<float?> AverageAsync(IQueryable<float?> source, CancellationToken cancellationToken);
        Task<double> AverageAsync(IQueryable<double> source);
        Task<double> AverageAsync(IQueryable<double> source, CancellationToken cancellationToken);
        Task<double?> AverageAsync(IQueryable<double?> source);
        Task<double?> AverageAsync(IQueryable<double?> source, CancellationToken cancellationToken);
        Task<Decimal> AverageAsync(IQueryable<Decimal> source);
        Task<Decimal> AverageAsync(IQueryable<Decimal> source, CancellationToken cancellationToken);
        Task<Decimal?> AverageAsync(IQueryable<Decimal?> source);
        Task<Decimal?> AverageAsync(IQueryable<Decimal?> source, CancellationToken cancellationToken);
        Task<double> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, int>> selector);
        Task<double> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, int>> selector, CancellationToken cancellationToken);
        Task<double?> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, int?>> selector);
        Task<double?> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, int?>> selector, CancellationToken cancellationToken);
        Task<double> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, long>> selector);
        Task<double> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, long>> selector, CancellationToken cancellationToken);
        Task<double?> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, long?>> selector);
        Task<double?> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, long?>> selector, CancellationToken cancellationToken);
        Task<float> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, float>> selector);
        Task<float> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, float>> selector, CancellationToken cancellationToken);
        Task<float?> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, float?>> selector);
        Task<float?> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, float?>> selector, CancellationToken cancellationToken);
        Task<double> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, double>> selector);
        Task<double> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, double>> selector, CancellationToken cancellationToken);
        Task<double?> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, double?>> selector);
        Task<double?> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, double?>> selector, CancellationToken cancellationToken);
        Task<Decimal> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, Decimal>> selector);
        Task<Decimal> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, Decimal>> selector, CancellationToken cancellationToken);
        Task<Decimal?> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, Decimal?>> selector);
        Task<Decimal?> AverageAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, Decimal?>> selector, CancellationToken cancellationToken);
    }
}